### ISSUE TITLE
Enable Security Advisories / Security Contact

### ISSUE THREAD

**Issue by R3x** [9sako6/imgcmp#271]
Hello,

I would like to report a security vulnerability in private, I was not able to find a security contact for this repository and there is no security policy and private reporting is disabled as well. What would be a good contact to reach out to? Or would you be open to enabling private vulnerability reporting for the repository?

**Comment by 9sako6** [comment]
Hello @R3x,

Thank you for reporting the vulnerability. I have enabled private vulnerability reporting for this repository.

Please let me know if there are any other actions we should take.

Best regards,
